### ISSUE TITLE
On Linux, how do I run the ytinu executable?

### ISSUE THREAD

**Issue by hub2git** [ytinu-mods/ytinu#1]
I'm on Linux Mint. 
I'm following the steps on https://github.com/ytinu-mods/ytinu. It says  that "step 1" is to download the program. So I  downloaded  https://github.com/ytinu-mods/ytinu/releases/download/v0.1.0/ytinu. 
Step 2 is to run it. How do I do so?

P.S. A link in "step 2" is a 404. https://bepinex.github.io/bepinex_docs/v5.3/articles/advanced/steam_interop.html#2-set-up-permissions

**Comment by benediktwerner** [comment]
Thanks, fixed the link.

As for running the executable, I'd think a Linux user should be able to figure that out 😅

Usually, double-clicking the executable in whatever file explorer you're using should work. If not, maybe your file explorer has a context-menu option to run it. Or just execute it from your terminal.
